### ISSUE TITLE
Aimage Seems to timeout often

### ISSUE THREAD

**Issue by Strider27** [zhaobenny/bz-cogs#38]
Thanks for a handy cog, unfortunately it seems to timeout most of the time on lower end hardware.

I keep getting this 9 out of 10 times when running /imagine "Command 'imagine' raised an exception: NotFound: 404 Not Found" in the Docker log.
Doing some googling shows that slash commands timeout after 3 seconds if no response is given, looks like my redbot instance is too slow.
According to stackoverflow, one solution is to use defer(), any chance it can be tweaked?

**Comment by zhaobenny** [comment]
The response should be deferred already.

https://github.com/zhaobenny/bz-cogs/blob/dd573984b68c542f14d5757d659def474e6868bd/aimage/functions.py#L41

Just to confirm a few things: 

- Is the slash commands properly sync'ed up?
- Are you running this with a stable-diffusion-webui endpoint?
- Is the error occuring when it's attempting to find autocompletions terms or generating the image? 
- What are your specs for the hardware you are on?

**Comment by Strider27** [comment]
Ok this might be long,

- slash commands seem to be synced, the suggestion box comes up without any issues, including all the options etc. not quite sure how to check past that.
- tried automatic1111 and sd-forge (fork of automatic) (haha, no not on the same hardware, it is running on Ryzen 9 3900x, 32gb RAM, RTX 4070 12GB VRAM, webui instance is on a sata ssd, can be moved to NVME but I don't think that's the problem)
- Error occurs after sending the command, it either says `"Sending Command"` for a moment and then returns `"The application did not respond"` or stays stuck on `" ...Scarlet is thinking"` indefinitely (scarlett is the name of the redbot in my case) in both cases nothing in sd-webui console.

When it returns `"The application did not respond"` I get the following in the docker log
```
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
[2024-02-19 20:30:51] [ERROR] red: Exception in command 'imagine'
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 184, in imagine_app
    await self.generate_image(interaction,
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 41, in generate_image
    await context.response.defer(thinking=True)
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
[2024-02-19 20:30:51] [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py:1087> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 184, in imagine_app
    await self.generate_image(interaction,
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 41, in generate_image
    await context.response.defer(thinking=True)
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1252, in _call
    await self.on_error(interaction, e)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 296, in on_error
    await self._send_from_interaction(
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 260, in _send_from_interaction
    return await interaction.response.send_message(*args, ephemeral=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

When it gets stuck on " ...Scarlet is thinking" there is nothing in the docker logs.
- Redbot is running in a docker container under Unraid both docker image and the entirety of the redbot container are running on a sata ssd array, the hardware specs are (HP Microserver Gen 8, Xeon E3-1265L V2 @ 2.50GHz 4 Cores 8 Threads, 16GB RAM)

Sometimes short prompts get through, i.e. `/imagine black cat` but have not been able to get a single complex prompt to work.

In all cases I barely notice any hardware utilisation by the docker container.

**Comment by Strider27** [comment]
Additionally trying to upscale the occasionally successful prompts returns `This interaction failed` with the following in the docker log
```
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
[2024-02-19 20:53:31] [ERROR] discord.ui.view: Ignoring exception in view <ImageActions timeout=300 children=4> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=True label=None emoji=<PartialEmoji animated=False name='🔄' id=None> row=None>
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/data/cogs/CogManager/cogs/aimage/views.py", line 69, in regenerate_image
    await self.generate_image(interaction, payload=self.payload)
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 41, in generate_image
    await context.response.defer(thinking=True)
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

**Comment by Strider27** [comment]
Here you go:

```
[2024-02-19 22:49:35] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - start generate_image function
[2024-02-19 22:49:35] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - Deferring message
[2024-02-19 22:49:35] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - object is <class 'discord.interactions.Interaction'>
[2024-02-19 22:49:35] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - raw data {
    "type": 1,
    "options": [
        {
            "value": "black cat",
            "type": 3,
            "name": "prompt"
        }
    ],
    "name": "imagine",
    "id": "1208583487888822325"
}
[2024-02-19 22:49:35] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction created at 2024-02-19 22:49:35.848000+00:00
[2024-02-19 22:49:35] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction expires at 2024-02-19 23:04:35.848000+00:00
[2024-02-19 22:49:35] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction is expired: False
[2024-02-19 22:49:39] [ERROR] red: Exception in command 'imagine'
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 186, in imagine_app
    await self.generate_image(interaction,
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 48, in generate_image
    await context.response.defer(thinking=True)
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
[2024-02-19 22:49:39] [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py:1087> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 186, in imagine_app
    await self.generate_image(interaction,
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 48, in generate_image
    await context.response.defer(thinking=True)
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1252, in _call
    await self.on_error(interaction, e)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 296, in on_error
    await self._send_from_interaction(
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 260, in _send_from_interaction
    return await interaction.response.send_message(*args, ephemeral=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

**Comment by zhaobenny** [comment]
Maybe it's taking more then 5 seconds before the deferral..

I added timers to the logs, can you pull the updates and output the logs again?

**Comment by Strider27** [comment]
Couldn't trigger error state with short prompts had to add a bit more to it:

```
[2024-02-19 22:59:20] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction created at 2024-02-19 22:59:20.507000+00:00
[2024-02-19 22:59:20] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction expires at 2024-02-19 23:14:20.507000+00:00
[2024-02-19 22:59:20] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction is expired: False
[2024-02-19 22:59:20] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - Message deferred!
[2024-02-19 22:59:44] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - start generate_image function
[2024-02-19 22:59:44] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - Deferring message
[2024-02-19 22:59:44] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - object is <class 'discord.interactions.Interaction'>
[2024-02-19 22:59:44] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - raw data {
    "type": 1,
    "options": [
        {
            "value": "A strikingly majestic MaineCoon cat, its fur exhibiting a stunning blend of colors, from rich browns to lustrous blacks, reminiscent of the intricate strokes of a master painter.",
            "type": 3,
            "name": "prompt"
        }
    ],
    "name": "imagine",
    "id": "1208583487888822325"
}
[2024-02-19 22:59:44] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction created at 2024-02-19 22:59:43.948000+00:00
[2024-02-19 22:59:44] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction expires at 2024-02-19 23:14:43.948000+00:00
[2024-02-19 22:59:44] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction is expired: False
[2024-02-19 22:59:47] [ERROR] red: Exception in command 'imagine'
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 186, in imagine_app
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 48, in generate_image
    logger.info(f"gh issue troubleshoot - interaction is expired: {context.is_expired()}")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
[2024-02-19 22:59:47] [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py:1087> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 186, in imagine_app
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 48, in generate_image
    logger.info(f"gh issue troubleshoot - interaction is expired: {context.is_expired()}")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1252, in _call
    await self.on_error(interaction, e)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 296, in on_error
    await self._send_from_interaction(
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 260, in _send_from_interaction
    return await interaction.response.send_message(*args, ephemeral=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

**Comment by Strider27** [comment]
Sorry deleted last reply, didn't reload the cog after update, requested log output below:

```
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - imagine_app called at 1708384318.6170866
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - start generate_image function
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - Deferring message
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - object is <class 'discord.interactions.Interaction'>
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - raw data {
    "type": 1,
    "options": [
        {
            "value": "black cat",
            "type": 3,
            "name": "prompt"
        }
    ],
    "name": "imagine",
    "id": "1208583487888822325"
}
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction created at 2024-02-19 23:11:58.479000+00:00
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction expires at 2024-02-19 23:26:58.479000+00:00
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - interaction is expired: False
[2024-02-19 23:11:58] [INFO] red.bz_cogs.aimage: gh issue troubleshoot - trying to defer at 1708384318.6378918
[2024-02-19 23:12:01] [ERROR] red: Exception in command 'imagine'
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 190, in imagine_app
    await self.generate_image(interaction,
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 50, in generate_image
    await context.response.defer(thinking=True)
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
[2024-02-19 23:12:02] [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py:1087> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 190, in imagine_app
    await self.generate_image(interaction,
  File "/data/cogs/CogManager/cogs/aimage/functions.py", line 50, in generate_image
    await context.response.defer(thinking=True)
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1252, in _call
    await self.on_error(interaction, e)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 296, in on_error
    await self._send_from_interaction(
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 260, in _send_from_interaction
    return await interaction.response.send_message(*args, ephemeral=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

**Comment by zhaobenny** [comment]
Looks like it was taking more then >5 seconds somehow (guess that's python for you)

I pushed changes to the main branch to move the defers earlier, should be fixed there, let me know if it works.

**Comment by Strider27** [comment]
Still getting the same error, also when bot is stuck thinking I got this in the log:
```
[2024-02-19 23:48:47] [WARNING] py.warnings: /data/cogs/CogManager/cogs/aimage/aimage.py:187: RuntimeWarning: coroutine 'Functions.send_response' was never awaited
  await self.generate_image(interaction,


```

Cant confirm if it pulled latest version,
Any way to check what version I have?

I did the following:
I removed debug branch with `[p]repo delete bz-cogs`
added main branch with `[p]repo add bz-cogs https://github.com/zhaobenny/bz-cogs`
Ran `[p]repo update`
Then `[p]cog update`

It returned `All installed cogs are already up to date`

So deleted aimage with `[p]cog uninstall aimage`
ran `[p]repo update`
then `[p]cog install bz-cogs aimage` and `load aimage`

**Comment by zhaobenny** [comment]
> Ran `[p]repo update`
> Then `[p]cog update`

Yup, looks right.

Some awaits were missing in the code. Should be resolved now for the final time...

**Comment by Strider27** [comment]
Thanks for that, Updated,

Short prompts are now working reliably, longer prompts return: `Prompt contains blacklisted words!`

The prompt is `A strikingly majestic MaineCoon cat, its fur exhibiting a stunning blend of colors, from rich browns to lustrous blacks, reminiscent of the intricate strokes of a master painter.`

runing `[p]aimage blacklist list` returns `Error in command 'aimage blacklist list'. Check your console or logs for details.`

Logs show this:
```
[2024-02-20 00:04:33] [ERROR] red: Exception in command 'aimage blacklist list'
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^
TypeError: Settings.blacklist_list() missing 1 required positional argument: 'ctx'
```

Running `[p]aimageowner blacklist list` results in no reply, the bot deleted the command though.

The blacklist is default, I can try looking at the source in GitHub no words match from the prompt.

**Comment by Strider27** [comment]
Still getting this randomly

```
[2024-02-20 00:15:01] [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='CommandTree-invoker' coro=<CommandTree._from_interaction.<locals>.wrapper() done, defined at /data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py:1087> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/aimage/aimage.py", line 178, in imagine_app
    await interaction.response.defer(thinking=True)
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 661, in defer
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "/data/venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1252, in _call
    await self.on_error(interaction, e)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 296, in on_error
    await self._send_from_interaction(
  File "/data/venv/lib/python3.11/site-packages/redbot/core/tree.py", line 260, in _send_from_interaction
    return await interaction.response.send_message(*args, ephemeral=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

**Comment by zhaobenny** [comment]
> runing `[p]aimage blacklist list` returns `Error in command 'aimage blacklist list'. Check your console or logs for details.`

Fixed this, another minor oversight again. (woops)

> Still getting this randomly, but not as often as before, for both short and longer prompts.

Not sure why it's taking >5 seconds to defer the interaction when it's the first thing that occurs,

Does this occur with other slash commands? 
Does the bot have a good connection to Discord servers?

**Comment by Strider27** [comment]
> Does this occur with other slash commands?

Have no other slash commands enabled on Redbot but have another very basic discord bot on the same server in another container which uses 2 slash command with no problems.

> Does the bot have a good connection to Discord servers?
Seems to be, ping to discord voice servers 26ms, to local Google Cloud and Cloudflare datacentres under 30ms. Connection is 2Gbit Down, 200Mbit Up, with average ping of 14ms under load to a regional datacentre. No disconnects etc.

**Comment by zhaobenny** [comment]
Could you try other slash commands on Redbot? 

Seems like you shouldn't be bottlenecked hardware/network wise, and the cog code should be fine enough. Not really sure what else could be the problem. 🤔

**Comment by Strider27** [comment]
> Could you try other slash commands on Redbot?

Oh Wow!!! enabled some other cogs with slash commands and you are right! Other Redbot slash commands are also intermittent, sorry for wasting your time! I guess now have to try to figure out what's going on with Redbot container. (a bot in another container has no issues with slash commands)

**Comment by zhaobenny** [comment]
No problem, got some minor bugs fixed anyways as part of it 😂
